/* ============================================================
   MISSIONS - Misiones secundarias por departamento
   Disponibles desde día 18 cuando el jugador está esperando
   ============================================================ */
window.MISSIONS = {
  operations: [
    { id: 'ops-m1', title: '🔧 Mantenimiento preventivo', desc: 'Revisaste la línea y encontraste un rodamiento desgastado. ¿Lo cambias ahora ($2M) o esperas al fin de semana?', optA: 'Cambiar ya', optB: 'Esperar', rewardA: { cash: 5000000, bsc: { bsc_internal: 3 } }, rewardB: { cash: 0, bsc: { bsc_internal: -2 } }, insightA: '✅ Evitaste una parada no programada. Costo de reparar en falla: $15M.', insightB: '⚠️ El rodamiento reventó el lunes. Parada de 6 horas.' },
    { id: 'ops-m2', title: '📦 Optimizar empaque', desc: 'Tu operario más experimentado sugiere cambiar el orden de empaque para ahorrar 8 segundos/paquete. ¿Implementas?', optA: 'Implementar', optB: 'Dejarlo como está', rewardA: { cash: 8000000, bsc: { bsc_internal: 4, bsc_learning: 2 } }, rewardB: { cash: 0, bsc: {} }, insightA: '✅ 8 seg × 5000 paq/día = 11 horas/día liberadas. Productividad sube.', insightB: '⚠️ La competencia ya lo hace así.' },
    { id: 'ops-m3', title: '🌡️ Control de temperatura', desc: 'El aceite de fritura está a 178°C. La receta dice 175°C ± 3°C. ¿Ajustas o está dentro del rango?', optA: 'Ajustar a 175°C', optB: 'Está bien así', rewardA: { cash: 3000000, bsc: { bsc_internal: 2, bsc_customer: 2 } }, rewardB: { cash: 2000000, bsc: { bsc_internal: 1 } }, insightA: '✅ Centrar en el objetivo minimiza variabilidad. Concepto: control de proceso.', insightB: '💡 Está dentro del rango (175±3), pero no centrado.' },
    { id: 'ops-m4', title: '🚛 Ruta de despacho', desc: 'Datos muestran que la ruta norte tarda en promedio 45min (σ=12) vs ruta sur 50min (σ=5). ¿Cuál eliges para un pedido urgente?', optA: 'Ruta norte (más rápida)', optB: 'Ruta sur (más consistente)', rewardA: { cash: 4000000, bsc: { bsc_customer: 2 } }, rewardB: { cash: 6000000, bsc: { bsc_customer: 4 } }, insightA: '⚠️ Norte es más rápida EN PROMEDIO pero con σ=12 puede tardar 69min (P95).', insightB: '✅ Para urgente, consistencia > velocidad promedio. P(>60min) es mucho menor.' },
    { id: 'ops-m5', title: '♻️ Reusar aceite', desc: 'El aceite tiene 3 usos. Calidad dice que al 4to uso la acidez sube de 0.5% a 0.9%. Límite INVIMA: 1%. ¿Un uso más?', optA: 'Cambiar aceite', optB: 'Un uso más', rewardA: { cash: -2000000, bsc: { bsc_internal: 3, bsc_customer: 2 } }, rewardB: { cash: 3000000, bsc: { bsc_internal: -2, bsc_customer: -1 } }, insightA: '✅ Margen de seguridad. Con σ de acidez, podrías superar 1% en el 4to uso.', insightB: '⚠️ 0.9% promedio pero si σ=0.15, P(>1%) ≈ 25%. Arriesgado.' },
  ],
  finance: [
    { id: 'fin-m1', title: '💳 Cobrar cartera', desc: 'Cliente debe $12M con 45 días de mora. Ofreces 10% descuento por pago inmediato. ¿Vale la pena?', optA: 'Ofrecer descuento', optB: 'Cobrar completo', rewardA: { cash: 10000000, bsc: { bsc_financial: 3 } }, rewardB: { cash: 3000000, bsc: { bsc_financial: 1 } }, insightA: '✅ $10.8M hoy > $12M en 90 días. Valor del dinero en el tiempo.', insightB: '⚠️ Historial: 30% de morosos a 45 días nunca pagan.' },
    { id: 'fin-m2', title: '📊 Revisar presupuesto', desc: 'Gastaste 62% del presupuesto en 58% del tiempo. ¿Ajustas o sigues?', optA: 'Ajustar gastos', optB: 'Seguir igual', rewardA: { cash: 5000000, bsc: { bsc_financial: 4 } }, rewardB: { cash: 0, bsc: { bsc_financial: -2 } }, insightA: '✅ Corregir a tiempo evita sobregiros. Tasa de gasto = 62/58 = 1.07x.', insightB: '⚠️ Al cierre estarás al 107% del presupuesto.' },
    { id: 'fin-m3', title: '🏦 CDT a 90 días', desc: 'Tienes $30M ociosos. CDT a 90 días al 12% E.A. ¿Invertir?', optA: 'Invertir en CDT', optB: 'Mantener liquidez', rewardA: { cash: 7000000, bsc: { bsc_financial: 3 } }, rewardB: { cash: 2000000, bsc: { bsc_financial: 1 } }, insightA: '✅ $30M × (1.12)^(90/365) ≈ $30.85M. Rendimiento seguro.', insightB: '💡 Liquidez tiene valor, pero el costo de oportunidad es $850K.' },
    { id: 'fin-m4', title: '🧾 Factura sospechosa', desc: 'Factura de $8M de un proveedor que normalmente cobra $5M-$6M. ¿Investigar o pagar?', optA: 'Investigar', optB: 'Pagar', rewardA: { cash: 6000000, bsc: { bsc_financial: 4, bsc_internal: 2 } }, rewardB: { cash: -3000000, bsc: { bsc_financial: -3 } }, insightA: '✅ Era un cobro duplicado. Ahorraste $8M menos costo de investigar.', insightB: '❌ Pagaste de más. La factura tenía items duplicados.' },
    { id: 'fin-m5', title: '💰 Renegociar seguro', desc: 'El seguro de la planta cuesta $4M/año. Otra aseguradora ofrece $3.2M pero con deducible más alto.', optA: 'Cambiar aseguradora', optB: 'Quedarse', rewardA: { cash: 4000000, bsc: { bsc_financial: 2 } }, rewardB: { cash: 1000000, bsc: { bsc_financial: 1 } }, insightA: '💡 Ahorras $800K/año. Pero E(costo siniestro con deducible alto) sube.', insightB: '✅ Seguro conservador protege contra eventos de cola pesada.' },
  ],
  marketing: [
    { id: 'mkt-m1', title: '📱 Post en Instagram', desc: 'Tu community manager tiene un reel listo. ¿Publicar a las 12pm (más alcance) o 7pm (más engagement)?', optA: 'Publicar a las 12pm', optB: 'Publicar a las 7pm', rewardA: { cash: 4000000, bsc: { bsc_customer: 3 } }, rewardB: { cash: 6000000, bsc: { bsc_customer: 4 } }, insightA: '💡 Más alcance pero tasa de conversión 2.1%.', insightB: '✅ Menos alcance pero tasa de conversión 4.8%. ROI mayor.' },
    { id: 'mkt-m2', title: '🎁 Promo 2x1', desc: 'Hacer 2x1 este fin de semana. Margen baja 50% pero volumen sube ~80%. ¿Lanzar?', optA: 'Lanzar promo', optB: 'No hacer promo', rewardA: { cash: 8000000, bsc: { bsc_customer: 5, bsc_financial: -2 } }, rewardB: { cash: 2000000, bsc: { bsc_financial: 1 } }, insightA: '✅ Volumen × 1.8 con margen × 0.5 = ingreso neto × 0.9. Casi igual pero ganas clientes nuevos.', insightB: '💡 Sin promo mantienes margen pero no creces.' },
    { id: 'mkt-m3', title: '🏪 Exhibidor en D1', desc: 'D1 ofrece exhibidor especial por $3M/mes. Historial: sube ventas 25% en esa tienda.', optA: 'Tomar exhibidor', optB: 'Pasar', rewardA: { cash: 7000000, bsc: { bsc_customer: 3, bsc_financial: 2 } }, rewardB: { cash: 1000000, bsc: {} }, insightA: '✅ Si ventas base = $15M/mes en D1, +25% = $3.75M extra. ROI positivo.', insightB: '⚠️ La competencia tomó tu exhibidor.' },
    { id: 'mkt-m4', title: '⭐ Responder reseña negativa', desc: 'Cliente dejó 1 estrella en Google: "paquete medio vacío". 340 personas la vieron.', optA: 'Responder públicamente + compensar', optB: 'Ignorar', rewardA: { cash: 2000000, bsc: { bsc_customer: 5 } }, rewardB: { cash: 0, bsc: { bsc_customer: -4 } }, insightA: '✅ Respuesta empática convierte detractores en promotores. NPS sube.', insightB: '❌ 340 personas vieron la queja sin respuesta. Daño silencioso.' },
    { id: 'mkt-m5', title: '🎨 Rediseño de empaque', desc: 'Focus group de 15 personas: 11 prefieren empaque nuevo (73%). ¿Suficiente para cambiar?', optA: 'Cambiar empaque', optB: 'Más investigación', rewardA: { cash: 5000000, bsc: { bsc_customer: 3 } }, rewardB: { cash: 3000000, bsc: { bsc_learning: 3 } }, insightA: '⚠️ n=15 es pequeño. IC: [45%, 92%]. Incluye 50%. Arriesgado.', insightB: '✅ Con n=15, el IC es muy amplio. Mejor investigar más.' },
  ],
  hr: [
    { id: 'hr-m1', title: '🎂 Cumpleaños del equipo', desc: 'Esta semana cumplen 3 operarios. ¿Torta y 30 min de celebración ($500K) o solo mensaje?', optA: 'Celebrar', optB: 'Solo mensaje', rewardA: { cash: 2000000, bsc: { bsc_learning: 4, bsc_internal: 2 } }, rewardB: { cash: 500000, bsc: { bsc_learning: 1 } }, insightA: '✅ Estudios: reconocimiento personal sube productividad 12% la semana siguiente.', insightB: '💡 Funcional pero no genera vínculo emocional.' },
    { id: 'hr-m2', title: '🏥 Operario con dolor de espalda', desc: 'Un operario se queja de dolor lumbar. Médico dice que puede trabajar pero recomienda pausa activa.', optA: 'Implementar pausas activas', optB: 'Que siga normal', rewardA: { cash: 3000000, bsc: { bsc_learning: 3, bsc_internal: 3 } }, rewardB: { cash: 0, bsc: { bsc_internal: -3, bsc_learning: -2 } }, insightA: '✅ Prevención > tratamiento. Costo de incapacidad por lesión: $8M+.', insightB: '❌ A las 2 semanas pidió incapacidad. Costo: $8M en reemplazo temporal.' },
    { id: 'hr-m3', title: '📚 Capacitación exprés', desc: 'SENA ofrece curso de BPM de 4 horas gratis. Pero perderías media jornada de producción.', optA: 'Enviar al equipo', optB: 'No hay tiempo', rewardA: { cash: 4000000, bsc: { bsc_learning: 5, bsc_internal: 2 } }, rewardB: { cash: 1000000, bsc: { bsc_learning: -2 } }, insightA: '✅ Gratis + certificación. El costo de oportunidad ($3M producción) se recupera en 1 semana con mejores prácticas.', insightB: '⚠️ El equipo rival fue. Ahora tienen certificación BPM y tú no.' },
    { id: 'hr-m4', title: '🤝 Resolver conflicto', desc: 'Dos operarios discutieron fuerte. El equipo está tenso. ¿Mediar hoy o dejar que se calme solo?', optA: 'Mediar ahora', optB: 'Esperar', rewardA: { cash: 3000000, bsc: { bsc_learning: 3, bsc_internal: 4 } }, rewardB: { cash: 0, bsc: { bsc_internal: -4 } }, insightA: '✅ Mediación inmediata evita escalamiento. El equipo vuelve a ritmo en 1 día.', insightB: '❌ La tensión duró 2 semanas. Productividad cayó 15%.' },
    { id: 'hr-m5', title: '💪 Reconocimiento público', desc: 'Tu operario más productivo (μ+2σ en rendimiento) no ha recibido reconocimiento en 6 meses.', optA: 'Reconocer en reunión', optB: 'Ya le pagan bien', rewardA: { cash: 5000000, bsc: { bsc_learning: 5, bsc_internal: 3 } }, rewardB: { cash: 0, bsc: { bsc_learning: -2, bsc_internal: -1 } }, insightA: '✅ μ+2σ = top 2.3%. Este talento es estadísticamente raro. Cuidarlo cuesta poco.', insightB: '⚠️ Al mes siguiente renunció. Reemplazar talento top 2.3% cuesta 3x su salario.' },
  ],
  analyst: [
    { id: 'dat-m1', title: '📈 Limpiar datos', desc: 'Encontraste 3 outliers en la base de ventas (valores 10x fuera de lo normal). ¿Los eliminas o investigas?', optA: 'Investigar primero', optB: 'Eliminar', rewardA: { cash: 6000000, bsc: { bsc_learning: 5, bsc_financial: 2 } }, rewardB: { cash: 2000000, bsc: { bsc_learning: 1 } }, insightA: '✅ Eran ventas corporativas reales. Eliminarlas habría sesgado las proyecciones.', insightB: '⚠️ Eliminaste datos legítimos. Tu modelo ahora subestima la demanda.' },
    { id: 'dat-m2', title: '🔍 Automatizar reporte', desc: 'Haces un reporte manual cada semana (4 horas). Automatizarlo cuesta 16 horas una vez.', optA: 'Automatizar', optB: 'Seguir manual', rewardA: { cash: 7000000, bsc: { bsc_learning: 4, bsc_internal: 3 } }, rewardB: { cash: 1000000, bsc: {} }, insightA: '✅ 16h inversión / 4h ahorro = break-even en 4 semanas. Después es ganancia pura.', insightB: '⚠️ 4h/semana × 52 semanas = 208h/año en tarea repetitiva.' },
    { id: 'dat-m3', title: '🎯 Validar modelo', desc: 'Tu modelo de pronóstico tiene R²=0.85. El gerente quiere usarlo para una decisión de $50M. ¿Suficiente?', optA: 'Validar con datos nuevos', optB: 'R²=0.85 es suficiente', rewardA: { cash: 5000000, bsc: { bsc_learning: 5, bsc_financial: 3 } }, rewardB: { cash: 2000000, bsc: { bsc_learning: -2 } }, insightA: '✅ R² en datos de entrenamiento siempre es optimista. Validación cruzada dio R²=0.72. Diferente.', insightB: '⚠️ Overfitting. El modelo se veía bien pero falló en datos nuevos.' },
    { id: 'dat-m4', title: '📊 Dashboard para gerencia', desc: 'El gerente pide un dashboard "bonito" para inversionistas. ¿Priorizas diseño visual o precisión de datos?', optA: 'Balance: bonito Y preciso', optB: 'Lo que pida el jefe', rewardA: { cash: 5000000, bsc: { bsc_learning: 3, bsc_customer: 3 } }, rewardB: { cash: 3000000, bsc: { bsc_customer: 2, bsc_learning: -1 } }, insightA: '✅ Los mejores dashboards son claros Y precisos. Barras de error incluidas.', insightB: '💡 Bonito sin barras de error engaña. Si preguntan, no tendrás respuesta.' },
    { id: 'dat-m5', title: '⚡ Alerta temprana', desc: 'Tus datos muestran que las ventas de los últimos 5 días están 1.5σ por debajo de la media. ¿Alertar?', optA: 'Alertar al equipo', optB: 'Esperar más datos', rewardA: { cash: 8000000, bsc: { bsc_learning: 4, bsc_financial: 3 } }, rewardB: { cash: 2000000, bsc: { bsc_learning: 1 } }, insightA: '✅ 1.5σ por 5 días consecutivos tiene P < 0.3%. Algo está pasando. Alertar fue correcto.', insightB: '⚠️ Resultó ser un problema de distribución. Detectarlo tarde costó $20M.' },
  ]
};
